# Generated by Django 5.2.1 on 2025-05-11 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_newuser_description_newuser_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='description',
            field=models.TextField(default='Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='hourly_rate',
            field=models.IntegerField(default='1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='hours_week',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='type',
            field=models.CharField(choices=[('job_seeker', 'job_seeker'), ('company', 'company')], default='job_seeker', max_length=50),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
