# Generated by Django 5.2.1 on 2025-05-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_newuser_description_alter_newuser_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='name',
            field=models.CharField(default='seba', max_length=50),
            preserve_default=False,
        ),
    ]
