# Generated by Django 5.2.1 on 2025-05-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_workexperience_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='type',
        ),
    ]
